apiVersion: v1
kind: Service
metadata:
  name: kubia-service
spec:
  type: NodePort
  selector:
    app: kubia-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
